/** @type {import('tailwindcss').Config} */
const config = {
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'background':                '#101418',
        'surface':                   '#101418',
        'surface-dim':               '#101418',
        'surface-container-lowest':  '#0a0f13',
        'surface-container-low':     '#181c21',
        'surface-container':         '#1c2025',
        'surface-container-high':    '#262a2f',
        'surface-container-highest': '#31353a',
        'surface-variant':           '#31353a',
        'surface-bright':            '#36393f',
        'on-background':             '#e0e2e9',
        'on-surface':                '#e0e2e9',
        'on-surface-variant':        '#c1c6d7',
        'outline':                   '#8b90a0',
        'outline-variant':           '#414755',
        'primary':                   '#005bc1',
        'primary-container':         '#4b8eff',
        'primary-fixed-dim':         '#adc6ff',
        'on-primary':                '#ffffff',
        'inverse-surface':           '#e0e2e9',
        'inverse-on-surface':        '#2d3136',
        'error':                     '#ffb4ab',
        'error-container':           '#93000a',
        'on-error':                  '#690005',
      },
      borderRadius: {
        DEFAULT: '10px',
        none:    '0px',
        sm:      '6px',
        md:      '10px',
        lg:      '16px',
        xl:      '22px',
        '2xl':   '28px',
        '3xl':   '36px',
        full:    '9999px',
      },
      spacing: {
        'margin-desktop': '64px',
        'margin-mobile':  '16px',
        'stack-lg':       '48px',
        'stack-md':       '24px',
        'stack-sm':       '8px',
        'gutter':         '24px',
        'unit':           '4px',
      },
      fontFamily: {
        'headline-xl':        ['var(--font-archivo-narrow)', 'sans-serif'],
        'headline-lg':        ['var(--font-archivo-narrow)', 'sans-serif'],
        'headline-lg-mobile': ['var(--font-archivo-narrow)', 'sans-serif'],
        'data-display':       ['var(--font-archivo-narrow)', 'sans-serif'],
        'label-caps':         ['var(--font-hanken-grotesk)', 'sans-serif'],
        'body-md':            ['var(--font-hanken-grotesk)', 'sans-serif'],
        'body-lg':            ['var(--font-hanken-grotesk)', 'sans-serif'],
      },
      fontSize: {
        'headline-xl':        ['48px',  { lineHeight: '1.1',  letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg':        ['32px',  { lineHeight: '1.2',  letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px',  { lineHeight: '1.2',  fontWeight: '700' }],
        'data-display':       ['24px',  { lineHeight: '1',    letterSpacing: '0.05em',  fontWeight: '600' }],
        'body-lg':            ['18px',  { lineHeight: '1.6',  fontWeight: '400' }],
        'body-md':            ['16px',  { lineHeight: '1.6',  fontWeight: '400' }],
        'label-caps':         ['12px',  { lineHeight: '1',    letterSpacing: '0.1em',   fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}

module.exports = config
