import type { Metadata, Viewport } from 'next'
import Script from 'next/script'
import { Archivo_Narrow, Hanken_Grotesk } from 'next/font/google'
import './globals.css'
import JsonLd from '@/components/JsonLd'
import { organizationSchema } from '@/lib/schema'
import { SITE_URL, SITE_NAME } from '@/lib/site'

const GA_MEASUREMENT_ID = 'G-EJ0PF84W5E'

const archivoNarrow = Archivo_Narrow({
  subsets: ['latin'],
  variable: '--font-archivo-narrow',
  weight: ['400', '500', '600', '700'],
  style: ['normal', 'italic'],
  display: 'swap',
})

const hankenGrotesk = Hanken_Grotesk({
  subsets: ['latin'],
  variable: '--font-hanken-grotesk',
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  display: 'swap',
})

const TITLE_DEFAULT = 'WagSpeed | Mobile Dog Treadmill Service in Tri-Cities, WA'
const DESCRIPTION =
  'WagSpeed brings a professional dog treadmill to your driveway in the Tri-Cities — Kennewick, Pasco & Richland, WA. A climate-controlled van and an experienced handler give your dog a real 30-minute workout. Join the waitlist.'

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: TITLE_DEFAULT,
    template: `%s | ${SITE_NAME}`,
  },
  description: DESCRIPTION,
  applicationName: SITE_NAME,
  keywords: [
    'dog treadmill',
    'mobile dog treadmill',
    'dog fitness Tri-Cities',
    'dog exercise Kennewick',
    'dog treadmill Pasco',
    'dog workout Richland',
    'mobile dog gym',
    'dog weight loss',
    'canine conditioning',
    'dog exercise Tri-Cities WA',
  ],
  authors: [{ name: SITE_NAME }],
  creator: SITE_NAME,
  publisher: SITE_NAME,
  alternates: { canonical: '/' },
  category: 'Pet Services',
  icons: {
    icon: [
      { url: '/favicon.svg', type: 'image/svg+xml' },
      { url: '/logo.png',    type: 'image/png', sizes: '1536x1024' },
    ],
    apple: '/logo.png',
  },
  openGraph: {
    title: TITLE_DEFAULT,
    description: DESCRIPTION,
    url: '/',
    siteName: SITE_NAME,
    type: 'website',
    locale: 'en_US',
    // og:image is generated at exactly 1200x630 by app/opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: TITLE_DEFAULT,
    description: DESCRIPTION,
    // twitter:image is generated by app/twitter-image.tsx
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
      'max-snippet': -1,
      'max-video-preview': -1,
    },
  },
}

export const viewport: Viewport = {
  themeColor: '#101418',
  colorScheme: 'dark',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`dark ${archivoNarrow.variable} ${hankenGrotesk.variable}`}
    >
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        {children}

        {/* Site-wide structured data — Organization + LocalBusiness (service area) */}
        <JsonLd data={organizationSchema()} />

        {/* Google Analytics (gtag.js) */}
        <Script
          src={`https://www.googletagmanager.com/gtag/js?id=${GA_MEASUREMENT_ID}`}
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', '${GA_MEASUREMENT_ID}');
          `}
        </Script>
      </body>
    </html>
  )
}
